 return {
 override_enabled = true,
       unprepared = { -- "never", "rare", "default", "often", "always"
               berrybush = "often",
               cactus = "default",
               carrot = "often",
               mushroom = "default",
       },
       misc = {
               task_set = "default", -- Biomes: "classic", "cave_default"
               start_location = "default", -- Start: "plus", "darkness", "caves"
               autumn = "longseason", -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
               boons = "often", -- "never", "rare", "default", "often", "always"
               branching = "default", -- "never", "least", "default", "most"
               day = "longday", -- "default", "longday", "longdusk", "longnight", "noday", "nodusk", "nonight", "onlyday", "onlydusk", "onlynight"
               frograin = "never", -- "never", "rare", "default", "often", "always"
               lightning = "never", -- "never", "rare", "default", "often", "always"
               loop = "default", -- "never", "default", "always"
               season_start = "spring", -- "default", "winter", "spring", "summer", "random"
               spring = "default", -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
               summer = "shortseason", -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
               touchstone = "often", -- "never", "rare", "default", "often", "always"
               weather = "rare", -- "never", "rare", "default", "often", "always"
               wildfires = "never", -- "never", "rare", "default", "often", "always"
               winter = "default", -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
               world_size = "huge", -- "default", "medium", "large", "huge"
       },
       animals = { -- "never", "rare", "default", "often", "always"
               alternatehunt = "always",
               angrybees = "rare",
               beefalo = "often",
               beefaloheat = "default",
               bees = "default",
               birds = "default",
               butterfly = "default",
               buzzard = "default",
               catcoon = "default",
               frogs = "rare",
               hunt = "often",
               lightninggoat = "default",
               moles = "default",
               penguins = "always",
               perd = "default",
               pigs = "default",
               rabbits = "often",
               tallbirds = "default",
       },
       monsters = { -- "never", "rare", "default", "often", "always"
               bearger = "never",
               chess = "default",
               deciduousmonster = "default",
               deerclops = "never",
               dragonfly = "default",
               goosemoose = "never",
               houndmound = "default",
               hounds = "rare",
               krampus = "rare",
               liefs = "rare",
               lureplants = "rare",
               merm = "default",
               spiders = "default",
               tentacles = "default",
               walrus = "default",
       },
       resources = { -- "never", "rare", "default", "often", "always"
               flint = "often",
               flowers = "default",
               grass = "often",
               marshbush = "rare",
               meteorshowers = "rare",
               meteorspawner = "default",
               reeds = "default",
               rock = "often",
               rock_ice = "often",
               sapling = "often",
               trees = "often",
               tumbleweed = "often",
       }
}